[build]
publish="docs"
command="python3 --version && python3 scripts/get-pip.py && python3 -m pip install --user setuptools py-make poetry && python3 -m pymake setup && . ~/.bashrc && python3 --version && python3 -m pymake"
