[build]
publish="docs"
command="    python3 --version && python3 scripts/get-pip.py --user && python3 -m pip install --user setuptools py-make poetry && python3 -m pymake setup && . ~/.bashrc && pyenv install 3.8.1 && pyenv global 3.8.1 && python3 --version && python3 -m pymake"
